using System.IO;
using System.Security.Cryptography;
using Watchdog.TM;
using Watchdog.Licensing;
using ClosedXML.Excel;
using System.Net;
using System.Net.Sockets;
using System.Text.Json;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
internal static class Program {
 static int passed;static readonly string root=System.IO.Path.GetFullPath(System.IO.Path.Combine(Environment.CurrentDirectory,"work/test-"+DateTime.Now.ToString("yyyyMMddHHmmss")));
 [STAThread] static int Main(string[] args){Directory.CreateDirectory(root);if(args.Contains("--render"))return Render();try{Run().GetAwaiter().GetResult();Console.WriteLine($"PASS: {passed} checks. Evidence: {root}");return 0;}catch(Exception ex){Console.WriteLine(ex);return 1;}}
 static TmLicenseDocument SignTm(TmLicensePayload p,string privateKey){var bytes=JsonSerializer.SerializeToUtf8Bytes(p,new JsonSerializerOptions{PropertyNamingPolicy=JsonNamingPolicy.CamelCase});using var key=ECDsa.Create();key.ImportFromPem(privateKey);static string B(byte[] b)=>Convert.ToBase64String(b).TrimEnd('=').Replace('+','-').Replace('/','_');return new(B(bytes),B(key.SignData(bytes,HashAlgorithmName.SHA256,DSASignatureFormat.Rfc3279DerSequence)));}
 static void Check(bool value,string label){if(!value)throw new Exception("FAIL: "+label);passed++;Console.WriteLine("PASS "+label);}
 static void Reject(Action a,string name){bool rejected=false;try{a();}catch{rejected=true;}Check(rejected,name);}
 static async Task Run(){
 var automatic=new Configuration();automatic.Settings.Simulation=false;
 var liveController=new Controller{Protocol=Protocol.RTU};automatic.Controllers.Add(liveController);
 var liveSensor=new Sensor{ControllerId=liveController.Id,TemperatureOffset=4196};automatic.Sensors.Add(liveSensor);
 LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.SequenceEqual(new[]{liveSensor.Id}),"live startup restores eligible readings");
 liveSensor.TemperatureOffset=4197;liveController.PollSeconds=3;LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.Contains(liveSensor.Id),"sensor and controller edits keep live polling enabled");
 liveSensor.Enabled=false;LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.Count==0,"disabled sensor remains stopped");
 liveSensor.Enabled=true;liveSensor.Retired=true;LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.Count==0,"retired sensor remains stopped");
 liveSensor.Retired=false;liveController.Enabled=false;LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.Count==0,"disabled controller remains stopped");
 liveController.Enabled=true;liveController.Protocol=Protocol.Simulation;LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.Count==0,"demo controller excluded from automatic live polling");
 liveController.Protocol=Protocol.RTU;liveSensor.TemperatureOffset=null;LiveMonitoring.Apply(automatic);Check(automatic.Settings.CommissionedSensors.Count==0,"unmapped sensor excluded");
 liveSensor.TemperatureOffset=4196;LiveMonitoring.Apply(automatic);var restarted=JsonSerializer.Deserialize<Configuration>(JsonSerializer.Serialize(automatic))!;LiveMonitoring.Apply(restarted);Check(restarted.Settings.CommissionedSensors.Contains(liveSensor.Id)&&!restarted.Settings.Simulation,"live mode survives saved configuration and restart");
 automatic.Settings.Simulation=true;automatic.Settings.CommissionedSensors.Clear();LiveMonitoring.Apply(automatic);Check(automatic.Settings.Simulation&&automatic.Settings.CommissionedSensors.Count==0,"intentional demonstration mode preserved");
 var alarmSensor=new Sensor{SoftwareHighLimit=8,SoftwareLowLimit=2};
 Reading AlarmReading(double? value,string quality="VALID")=>new(DateTimeOffset.UtcNow,value,null,null,null,false,quality);
 Check(SoftwareAlarms.Evaluate(alarmSensor,AlarmReading(8.1))=="High","local high alarm above high limit");
 Check(SoftwareAlarms.Evaluate(alarmSensor,AlarmReading(1.9))=="Low","local low alarm below low limit");
 foreach(var value in new[]{2d,5d,8d})Check(SoftwareAlarms.Evaluate(alarmSensor,AlarmReading(value))=="Normal","alarm boundary and normal range");
 foreach(var quality in new[]{"OFFLINE","STALE","DISABLED","SENSOR FAULT"})Check(SoftwareAlarms.Evaluate(alarmSensor,AlarmReading(20,quality))=="Unavailable","invalid reading does not raise a current alarm");
 Check(SoftwareAlarms.Evaluate(alarmSensor,AlarmReading(null))=="Unavailable","missing temperature has no current alarm");
 Check(SoftwareAlarms.Evaluate(new Sensor(),AlarmReading(100))=="Normal","unconfigured software limits are off");
 var alarmConfig=Rules.Demo();alarmConfig.Sensors[0].SoftwareLowLimit=8;alarmConfig.Sensors[0].SoftwareHighLimit=2;Reject(()=>Rules.Validate(alarmConfig),"reversed software thresholds rejected");
 alarmConfig.Sensors[0].SoftwareLowLimit=2;alarmConfig.Sensors[0].SoftwareHighLimit=8;Rules.Validate(alarmConfig);
 var roundtrip=JsonSerializer.Deserialize<Configuration>(JsonSerializer.Serialize(alarmConfig))!;Check(roundtrip.Sensors[0].SoftwareHighLimit==8&&roundtrip.Sensors[0].SoftwareLowLimit==2,"software thresholds survive serialization");
 foreach(var workArea in new[]{new Rect(0,0,1536,816),new Rect(0,0,1280,680),new Rect(-1280,0,1280,720),new Rect(0,0,800,560)}){var bounds=WindowSizing.FitBounds(workArea,1370,960);Check(workArea.Contains(bounds)&&bounds.Top>=workArea.Top&&bounds.Height<workArea.Height,"window fits available desktop including scaled and small displays");}foreach(var empty in new[]{"","  "}){try{Security.License(empty);throw new Exception("Missing license accepted");}catch(InvalidDataException ex){Check(ex.Message.Contains("Import / Upgrade license")&&!ex.Message.Contains("JSON"),"missing license provides customer activation instructions");}}
try{Security.License("{broken");throw new Exception("Malformed license accepted");}catch(InvalidDataException ex){Check(ex.Message.Contains(".wdlicense")&&!ex.Message.Contains("BytePosition"),"malformed license hides parser internals");}Check(typeof(TmLicenseDocument).GetMethod("Create")==null,"customer verification assembly has no license signing API");
 Check(Rules.Decode([unchecked((ushort)-125)],ValueFormat.Int16,ByteOrder.ABCD,.1,0)==-12.5,"signed negative scaling");
 Check(Rules.Decode([0x3f80,0],ValueFormat.Float32,ByteOrder.ABCD,1,0)==1,"float32 decode");Check(Rules.Decode([0,0x3f80],ValueFormat.Float32,ByteOrder.CDAB,1,0)==1,"swapped word float");Check(Rules.Decode([0x803f,0],ValueFormat.Float32,ByteOrder.BADC,1,0)==1,"swapped byte float");
 var c=Rules.Demo();Rules.Validate(c);Check(c.Controllers.Count==3&&c.Sensors.Count==18,"18 sensor demonstration");var sensor=c.Sensors[0];var store=new Store(System.IO.Path.Combine(root,"test.db"));store.Save(c,"test","Created");var now=DateTimeOffset.UtcNow;store.Sample(new(sensor.Id,now,4.5,"VALID"));store.Sample(new(sensor.Id,now.AddSeconds(1),null,"OFFLINE"));sensor.Name="Renamed fridge";store.Save(c,"test","Renamed");var reopened=new Store(store.Path);Check(reopened.Load().Sensors[0].Name=="Renamed fridge"&&reopened.Samples(sensor.Id,now.AddSeconds(-1),now.AddMinutes(1)).Count==2,"rename and restart preserve history");
 sensor.EmailEnabled=true;sensor.Recipients="test@example.invalid";sensor.Reminders=true;sensor.ReminderMinutes=1;sensor.RecoveryEmail=true;
 Check(store.Observe(sensor,"HIGH",true,now,false),"alarm first activation");Check(!store.Observe(sensor,"HIGH",true,now.AddSeconds(2),false),"no duplicate alarm on next poll");var a=store.Alarms(c).Single();store.Ack(a.Id,"Operator");Check(store.Alarms(c).Single().Cleared==""&&store.Alarms(c).Single().Acknowledged!="","acknowledgement does not clear alarm");store.Observe(sensor,"HIGH",true,now.AddMinutes(2),false);store.Observe(sensor,"HIGH",true,now.AddMinutes(2).AddSeconds(1),false);Check(store.Emails(c).Count==2,"one initial and one reminder per interval");store.Observe(sensor,"HIGH",false,now.AddMinutes(3),false);Check(store.Alarms(c).Single().Cleared!=""&&store.Emails(c).Any(x=>x.Kind=="Recovery"),"recovery event and notification");Check(store.Emails(c).Single(x=>x.Kind=="Reminder").Status.StartsWith("Cancelled"),"recovery cancels pending reminders");store.Observe(sensor,"HIGH",true,now.AddMinutes(4),true);Check(store.Emails(c).Any(x=>x.Status=="Simulation — not sent"),"simulation emails suppressed");Check(new Store(store.Path).Emails(c).Count==4,"notification queue survives restart");
 var file=System.IO.Path.Combine(root,"export.xlsx");int count=Exporter.Export(store,sensor,c.Controllers[0],now.AddSeconds(-1),now.AddSeconds(2),file,CancellationToken.None);using(var book=new XLWorkbook(file)){var sheet=book.Worksheet(1);Check(count==2&&sheet.Cell(2,5).GetDouble()==4.5&&sheet.Cell(3,5).IsEmpty(),"Excel export has all selected rows and blank invalid value");Check(sheet.Cell(2,3).DataType==XLDataType.DateTime&&(sheet.Cell(2,4).DataType is XLDataType.Number or XLDataType.TimeSpan or XLDataType.DateTime),"Excel date and time cells are typed");}using(var cancel=new CancellationTokenSource()){cancel.Cancel();Reject(()=>Exporter.Export(store,sensor,c.Controllers[0],now,now.AddSeconds(2),file,cancel.Token),"export cancellation");}using(var locked=File.Open(file,FileMode.Open,FileAccess.ReadWrite,FileShare.None)){Reject(()=>Exporter.Export(store,sensor,c.Controllers[0],now,now.AddSeconds(2),file,CancellationToken.None),"locked export reports failure");}
 var backup=System.IO.Path.Combine(root,"backup.db");store.Backup(backup);sensor.Name="After backup";store.Save(c,"test","Changed");store.Restore(backup);Check(store.Load().Sensors[0].Name=="Renamed fridge"&&store.Samples(sensor.Id,now.AddSeconds(-1),now.AddMinutes(1)).Count==2,"consistent backup and restore");
 var secret="test-only-password-"+Guid.NewGuid();var hash=Security.Hash(secret);Check(Security.Verify(secret,hash)&&!Security.Verify("wrong",hash),"salted password verification");Check(Security.Hash(secret)!=hash,"unique password salts");Check(Security.Unprotect(Security.Protect(secret))==secret,"Windows protected SMTP secret round trip");
 using var key=ECDsa.Create(ECCurve.NamedCurves.nistP256);string pub=key.ExportSubjectPublicKeyInfoPem(),priv=key.ExportPkcs8PrivateKeyPem();var tm=new TmLicensePayload(2,"WatchdogTM",Guid.NewGuid(),"Test customer",Security.InstallationId,"Commercial",18,now.AddMinutes(-1),null);var signed=SignTm(tm,priv);Check(Security.License(signed.ToJson(),false,pub).MaximumTemperatureSensors==18,"valid offline TM activation signature");Reject(()=>Security.License(signed.ToJson(),false,pub,"wrong"),"wrong installation rejected");Check(!SignTm(tm with{Product="WatchdogEM"},priv).TryVerify(pub,out _,out _),"wrong product rejected");Check(!new TmLicenseDocument(signed.Payload+"A",signed.Signature).TryVerify(pub,out _,out _),"tampered license rejected");Reject(()=>Security.License("bad",false,pub),"malformed license rejected");var expired=SignTm(tm with{IssuedAtUtc=now.AddDays(-2),ExpiresAtUtc=now.AddDays(-1)},priv).ToJson();Reject(()=>Security.License(expired,false,pub),"expired activation rejected");Check(Security.License(expired,true,pub).MaximumTemperatureSensors==18,"expired license remains readable for continuity");
 var em=new LicensePayload(1,Guid.NewGuid(),"EM",Security.InstallationId,"Commercial",50,now,null);var emdoc=LicenseDocument.Create(em,priv);Check(emdoc.TryVerify(pub,out var emp,out _)&&emp!.MaximumMeters==50,"legacy EM format compatibility");Check(!LicenseDocument.Parse(signed.ToJson()).TryVerify(pub,out _,out _),"TM rejected by unchanged EM verifier");Check(!TmLicenseDocument.Parse(emdoc.ToJson()).TryVerify(pub,out _,out _),"EM rejected by TM verifier");
 var capacity=Rules.Demo();capacity.Settings.Simulation=false;capacity.Settings.LicenseJson=signed.ToJson();Security.Capacity(capacity,null,pub);capacity.Sensors[0].Enabled=false;capacity.Sensors.Add(new Sensor{ControllerId=capacity.Controllers[0].Id});Reject(()=>Security.Capacity(capacity,null,pub),"disabled sensors retain license slots");capacity.Sensors[0].Retired=true;Security.Capacity(capacity,null,pub);Check(true,"retirement releases a sensor slot");capacity.Sensors[0].Retired=false;Reject(()=>Security.Capacity(capacity,null,pub),"reactivation enforces capacity");capacity.Settings.LicenseJson=SignTm(tm with{MaximumTemperatureSensors=24},priv).ToJson();Security.Capacity(capacity,null,pub);Check(capacity.Sensors.Count==19,"capacity upgrade preserves sensors");capacity.Settings.LicenseJson=expired;var previous=JsonSerializer.Deserialize<Configuration>(JsonSerializer.Serialize(capacity))!;Security.Capacity(capacity,previous,pub);capacity.Sensors.Add(new Sensor{ControllerId=capacity.Controllers[0].Id});Reject(()=>Security.Capacity(capacity,previous,pub),"expired license blocks expansion but permits existing configuration");
 var queueConfig=Rules.Demo();queueConfig.Settings.Simulation=false;var qs=queueConfig.Sensors[0];qs.EmailEnabled=true;qs.Recipients="test@example.invalid";qs.RecoveryEmail=true;var queueStore=new Store(System.IO.Path.Combine(root,"queue.db"));queueStore.Save(queueConfig,"test","queue");var queueEngine=new MonitorEngine(queueConfig,queueStore);queueStore.Observe(qs,"HIGH",true,DateTimeOffset.UtcNow,false);var failedSender=new EmailWorker(queueEngine,(_,_,_,_,_)=>throw new MailKit.Security.AuthenticationException("test"));await failedSender.ProcessOne(CancellationToken.None);Check(queueStore.Emails(queueConfig).Single().Error.Contains("Authentication")&&queueStore.Emails(queueConfig).Single().Attempts==1,"SMTP authentication failure schedules retry");for(int n=0;n<4;n++){queueStore.Write(d=>Store.Run(d,"UPDATE email SET next=$0",Store.Utc(DateTimeOffset.UtcNow.AddSeconds(-1))));await failedSender.ProcessOne(CancellationToken.None);}Check(queueStore.Emails(queueConfig).Single().Status=="Failed","SMTP retries are bounded");queueStore.Write(d=>Store.Run(d,"UPDATE email SET status='Pending',attempts=0,next=$0",Store.Utc(DateTimeOffset.UtcNow)));queueStore.Observe(qs,"HIGH",false,DateTimeOffset.UtcNow,false);string delivered="";var fakeSender=new EmailWorker(queueEngine,(_,_,_,body,_)=>{delivered=body;return Task.CompletedTask;});await fakeSender.ProcessOne(CancellationToken.None);Check(delivered.Contains("has since cleared")&&queueStore.Emails(queueConfig).Any(x=>x.Status=="Submitted to mail server"),"delayed initial email includes observed recovery");await fakeSender.ProcessOne(CancellationToken.None);Check(queueStore.Emails(queueConfig).All(x=>x.Status=="Submitted to mail server"),"recovery submission status persists");queueConfig.Settings.Simulation=true;queueStore.Observe(qs,"HIGH",true,DateTimeOffset.UtcNow,true);int sends=0;await new EmailWorker(queueEngine,(_,_,_,_,_)=>{sends++;return Task.CompletedTask;}).ProcessOne(CancellationToken.None);Check(sends==0,"simulation hard-blocks queue submission");
 var reminderConfig=Rules.Demo();reminderConfig.Settings.Simulation=false;var rs=reminderConfig.Sensors[0];rs.EmailEnabled=true;rs.Recipients="test@example.invalid";rs.Reminders=true;rs.ReminderMinutes=1;var reminderStore=new Store(System.IO.Path.Combine(root,"reminder.db"));var observed=DateTimeOffset.UtcNow.AddMinutes(-3);reminderStore.Observe(rs,"HIGH",true,observed,false);var lastObserved=reminderStore.Alarms(reminderConfig).Single().LastObserved;reminderStore.QueueDueReminders(reminderConfig,DateTimeOffset.UtcNow);Check(reminderStore.Emails(reminderConfig).Any(x=>x.Kind=="Reminder")&&reminderStore.Alarms(reminderConfig).Single().LastObserved==lastObserved,"outage reminders preserve actual last observation time");
 var serialTransport=new Transport();int concurrent=0,maxConcurrent=0;await Task.WhenAll(Enumerable.Range(0,10).Select(_=>serialTransport.Serialize("COM-shared",async()=>{int current=Interlocked.Increment(ref concurrent);maxConcurrent=Math.Max(maxConcurrent,current);await Task.Delay(10);Interlocked.Decrement(ref concurrent);return true;},CancellationToken.None)));Check(maxConcurrent==1,"shared serial request gate never overlaps");
 var bad=Rules.Demo();bad.Controllers[0].Protocol=Protocol.RTU;bad.Controllers[1].Protocol=Protocol.RTU;bad.Controllers[1].BaudRate=19200;Reject(()=>Rules.Validate(bad),"conflicting shared serial settings rejected");bad.Controllers[1].BaudRate=9600;Reject(()=>Rules.Validate(bad),"duplicate slave address rejected");bad.Controllers[1].UnitId=2;Rules.Validate(bad);Check(true,"matching serial settings with separate slaves allowed");
 var sim=Rules.Demo();sim.Sensors[1].SampleSeconds=1;sim.Settings.AudibleAlarm=false;var simStore=new Store(System.IO.Path.Combine(root,"sim.db"));simStore.Save(sim,"test","simulation");var engine=new MonitorEngine(sim,simStore);engine.Start();await Task.Delay(2500);Check(engine.Readings.Count==18,"all controllers polled");var first=sim.Sensors[0];engine.Transport.Scenarios[first.Id]="High";await Task.Delay(2500);Check(engine.Display(first).High==true&&simStore.Alarms(sim).Count==1,"alarm detected before 10-minute history sample");engine.Transport.Scenarios[sim.Controllers[0].Id]="Offline";var other=engine.Readings[sim.Sensors[6].Id].At;await Task.Delay(2600);Check(engine.Display(first).High==true&&engine.Display(first).Quality=="OFFLINE","outage preserves alarm and marks offline");Check(engine.Readings[sim.Sensors[6].Id].At>other,"one failed controller does not block another");var sampleDeadline=DateTimeOffset.UtcNow.AddSeconds(8);while(DateTimeOffset.UtcNow<sampleDeadline&&!simStore.Samples(sim.Sensors[1].Id,now,DateTimeOffset.UtcNow).Any(x=>x.Temperature==null&&x.Quality.Contains("OFFLINE")))await Task.Delay(100);Check(simStore.Samples(sim.Sensors[1].Id,now,DateTimeOffset.UtcNow).Any(x=>x.Temperature==null&&x.Quality.Contains("OFFLINE")),"scheduled outage sample is blank rather than zero or old value");await engine.Stop();var restart=new MonitorEngine(sim,simStore);restart.Transport.Scenarios[sim.Controllers[0].Id]="Offline";restart.Start();Check(restart.Display(first).Quality!="VALID"&&restart.Display(first).High==true,"restart preserves last known alarm without showing it healthy");await restart.Stop();await TcpTest();
 }
 static async Task TcpTest(){var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();using var cancel=new CancellationTokenSource();ushort setpoint=80;int requests=0;var server=Task.Run(async()=>{try{while(!cancel.IsCancellationRequested){using var client=await listener.AcceptTcpClientAsync(cancel.Token);var stream=client.GetStream();while(!cancel.IsCancellationRequested){byte[] h=new byte[7];try{await stream.ReadExactlyAsync(h,cancel.Token);}catch(EndOfStreamException){break;}int length=(h[4]<<8|h[5])-1;var p=new byte[length];await stream.ReadExactlyAsync(p,cancel.Token);int address=p[1]<<8|p[2];requests++;if(p[0] is not (3 or 4)||address!=0)throw new Exception("Only the temperature register may be read");byte[] response=p[0] switch{1=>[1,1,1],2=>[2,1,0],3 or 4=>[p[0],2,(byte)((address==100?setpoint:45)>>8),(byte)(address==100?setpoint:45)],6=>p,_=>throw new Exception("Unexpected function")};if(p[0]==6)setpoint=(ushort)(p[3]<<8|p[4]);h[4]=0;h[5]=(byte)(response.Length+1);await stream.WriteAsync(h,cancel.Token);await stream.WriteAsync(response,cancel.Token);}}}catch(OperationCanceledException){}});try{var c=new Controller{Protocol=Protocol.TCP,Host="127.0.0.1",TcpPort=((IPEndPoint)listener.LocalEndpoint).Port};var s=new Sensor{TemperatureOffset=0,HighAlarmOffset=0,HighLimitOffset=100,Multiplier=.1,LimitMultiplier=.1};var transport=new Transport();var r=await transport.Read(c,s,false,CancellationToken.None);Check(r.Temperature==4.5&&r.High==null&&r.Low==null&&r.HighLimit==null&&!r.Fault&&requests==1,"live FC03 reads only temperature despite legacy alarm mappings");var bare=new Sensor{TemperatureOffset=0,Multiplier=.1,LowAlarmEnabled=true};Check(bare.Mapped,"temperature alone permits monitoring with legacy low alarm enabled");Check((await transport.Read(c,bare,false,CancellationToken.None)).Temperature==4.5,"continuous read requires no PLC alarm or limit mapping");Check(await transport.ReadTemperature(c,bare,CancellationToken.None)==4.5,"read-only connection test needs no alarm or write mappings");s.TemperatureFunction=RegisterFunction.Input04;Check((await transport.Read(c,s,false,CancellationToken.None)).Temperature==4.5,"Modbus TCP loopback FC04");Check(requests==4,"all requests are temperature-only FC03 or FC04 reads");}finally{cancel.Cancel();listener.Stop();await server;}}
 static int Render(){var app=new Application();var c=Rules.Demo();c.Settings.PasswordHash=Security.Hash("local-test-only-password");c.Settings.AudibleAlarm=false;foreach(var s in c.Sensors)s.SampleSeconds=1;var store=new Store(System.IO.Path.Combine(root,"ui.db"));store.Save(c,"test","UI smoke");var window=new MainWindow(store,c);window.Show();var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(4)};timer.Tick+=async(_,_)=>{timer.Stop();try{var tabs=(TabControl)typeof(MainWindow).GetField("tabs",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(window)!;for(int i=0;i<5;i++){tabs.SelectedIndex=i;window.UpdateLayout();var bmp=new RenderTargetBitmap((int)window.ActualWidth,(int)window.ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(window);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(bmp));using var f=File.Create(System.IO.Path.Combine(root,$"screen-{i+1}.png"));png.Save(f);}foreach(var item in new (object Model,string Name)[]{(new Controller{Protocol=Protocol.RTU,Name="DDC01 · First floor"},"controller-setup"),(new Sensor{Name="Fridge 01",Location="First floor"},"sensor-setup")}){var editor=new Editor(item.Model,"Watchdog TM — Setup"){Owner=window};editor.Show();editor.UpdateLayout();var eb=new RenderTargetBitmap((int)editor.ActualWidth,(int)editor.ActualHeight,96,96,PixelFormats.Pbgra32);eb.Render(editor);var ep=new PngBitmapEncoder();ep.Frames.Add(BitmapFrame.Create(eb));using(var ef=File.Create(System.IO.Path.Combine(root,item.Name+".png")))ep.Save(ef);editor.Close();}var eng=(MonitorEngine)typeof(MainWindow).GetField("engine",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(window)!;await eng.Stop();typeof(MainWindow).GetField("closing",BindingFlags.Instance|BindingFlags.NonPublic)!.SetValue(window,true);Console.WriteLine("UI renders: "+root);window.Close();app.Shutdown();}catch(Exception ex){Console.WriteLine(ex);app.Shutdown(1);}};timer.Start();return app.Run();}
}











